services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: nome_do_banco
    ports:
      - "5430:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
